# Refer to utils/config.py for definition and options.

version = "SIM"
task = "SIM"
dist = false
debug = false


[classifier]
n_channel = 4
num_classes = 20
load_size = 320
resume_checkpoint = "checkpoints/ckpt_best.pth"


[model]
resume_checkpoint = "checkpoints/ckpt_best.pth"


[model.arch]
encoder = "resnet50_BN"
n_channel = 11
atrous_rates = [12,24,36]
aspp_channel = 256


[data]
workers = 8
test_dir = "datasets/SIMD"


[log]
tensorboard_path = "./logs/tensorboard"
logging_path = "./logs/stdout"
checkpoint_path = "./checkpoints"


[test]
checkpoint = "best"
fast_eval = true
